INSERT INTO TODO (TODO_VALUE, IS_COMPLETED) VALUES('Jump in a lake', false)
INSERT INTO TODO (TODO_VALUE, IS_COMPLETED) VALUES('Take a break', false)
INSERT INTO TODO (TODO_VALUE, IS_COMPLETED) VALUES('Eat a sandwich', false)
INSERT INTO TODO (TODO_VALUE, IS_COMPLETED) VALUES('Drive a Tesla', false)

